--- #YAML:1.0
name:               Chess-PGN-EPD
version:            0.26
abstract:           Perl extension to produce and manipulate EPD text.
author:
    - Hugh S. Myers <hsmyers@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Chess::PGN::Moves:    0.04
    Chess::PGN::Parse:    0.19
    Cwd:                  3.31
    File::Spec::Functions:  3.3
    Storable:             2.21
    Test::More:           0.94
    Text::CSV:            1.18
    Try::Tiny:            0.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
