---
abstract: 'Perl extension to produce and manipulate EPD text.'
author:
  - 'Hugh S. Myers <hsmyers@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chess-PGN-EPD
no_index:
  directory:
    - t
    - inc
requires:
  Chess::PGN::Moves: 0.04
  Chess::PGN::Parse: 0.19
  Cwd: 3.31
  Storable: 2.21
  Test::More: 0.94
  Text::CSV: 1.18
  Try::Tiny: 0.06
version: 0.31
